#debloater-script

write-host "checking for news"
winget uninstall "News"
Write-Host "checking for mixed reality portal"
winget uninstall "Mixed reality portal"
Write-Host "checking for family"
winget uninstall "Family"
Write-Host "checking for Feedback hub"
winget uninstall "Feedback Hub"
Write-Host "checking for Films and tv"
#winget uninstall "Films and tv"
winget uninstall "Films en tv"
Write-Host "checking for xbox and related"
winget uninstall "xbox"
winget uninstall "Game Bar"
winget uninstall "Xbox Game Bar Plugin"
winget uninstall "Game Speech Window"
winget uninstall "xbox tcui"
winget uninstall "Xbox Identity Provider"
Write-Host "checking for whiteboard"
winget uninstall "Microsoft whiteboard"
Write-Host "checking for bing"
winget uninstall "Microsoft bing"
write-host "checking for maps"
winget uninstall "Windows Kaarten"
winget uninstall "windows maps"
Write-Host "checking for personen"
winget uninstall "Microsoft Personen"
Write-Host "checking for weather"
winget uninstall "MSN weer"
winget uninstall "MSN weather"
Write-Host "checking for dev home"
winget uninstall "dev home"